### PR TITLE
consider 'wamp.close.goodbye_and_out' a clean exit

### PR DESCRIPTION
**Pull request by meejah**
See #1370

### CODE REVIEW

**Comment by oberstet** [comment]
looks good .. not sure why CI is sad .. some weird "substitution blabla" error?

**Comment by meejah** [comment]
Weird .. I ran `tox -e flake8` successfully locally .. and just tried pushing "re-run all jobs" in case it was some transient / version issue but it seems to have failed again in the same way

**Comment by meejah** [comment]
(...and it's hard to imagine a *simpler* change than this PR ...)

**Comment by meejah** [comment]
ah, I had `tox 3.19.0` locally before; just upgraded (and got 3.21.2) and it fails similarly...

**Comment by meejah** [comment]
WAT?! It appears to be this line in the config (but it fails even before building the tox environment, so it's not *running* the line that's confusing tox, but merely *parsing the config*): https://github.com/crossbario/autobahn-python/blob/master/tox.ini#L190

**Comment by meejah** [comment]
(I'm pushing a change commenting-out that line just to see if the CI runs .. flake8 at least runs locally after that change)

**Comment by oberstet** [comment]
ok, weird!

> maybe it chokes on the `:` in `python -c "from autobahn import xbr; print('HAS_XBR={:}'.format(xbr.HAS_XBR))"` ? not sure .. forgot what it does here anyways;)

**Comment by meejah** [comment]
AAaaaaaaarrg, it seems that Tox figures it should look for `{}` anywhere at all and try to do .. substitutions? I guess .. so the "fix" in that last commit works, but also: WTF.

**Comment by oberstet** [comment]
yes, agreed, wtf! so I guess the take away is: be careful with literal code in tox ini files

**Comment by meejah** [comment]
I think it was probably this: https://github.com/tox-dev/tox/issues/1711 ... but also makes me wonder if that code was EVER doing what was intended, because I suspect Tox was replacing the `{}` with the os path-separator and so it never really did `HAS_XBR=True/False` correctly?

**Comment by oberstet** [comment]
wau. the issue you link: yeah, that looks like it. well. doing some silent substitutions on the literal lines in tox files .. is a bad idea. and yes

> makes me wonder if that code was EVER doing what was intended

indeed. it might never have actually worked as intended .. even though it did not break. mmh, well.

**Comment by oberstet** [comment]
@fijal rgd change https://github.com/crossbario/autobahn-python/commit/a468e5724b588ba51e3bbcad42317b906ac0606b#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449 was that intentional, related to above?

**Comment by fijal** [comment]
So one part is because CI complains about {} vs {:} (and fails flake8)

The second one is printing full information about the error as opposed to just Exception.

**Comment by oberstet** [comment]
thanks! merged it .. lets see https://github.com/crossbario/autobahn-python/actions/runs/510649942

**Pull request merged**
