### PR TITLE
Update license file to include contributors

### PR DESCRIPTION
**Pull request by muzzammilshahid**
As mentioned in https://github.com/crossbario/autobahn-js/issues/582#issuecomment-1908313491

### CODE REVIEW

**Comment by oberstet** [comment]
the fails https://github.com/crossbario/autobahn-python/actions/runs/7643742575/job/20829707541?pr=1628#step:8:70 are definitely unrelated .. I haven't analyzed the root cause .. likely some dependency changed its behavior making the previously working test here now fail:( oh well. yes, why don't we fix and pin all dependencies including CI here .. I spent countless hours of laying the ground for that, and actually do it, but I would not bet my life, well obviously I did not, address "all of it". tbh, I am also feeling that it might be a never ending, maybe unsolvable thing, at least very hard - in Python that is. anyways, that's just how I feel. your change is certainly welcome!

**Comment by yan12125** [comment]
Test failures are related to newer pytest-asyncio. If I use `pytest-asyncio<0.22`, all tests are still green. I'm not sure if it's an issue in newer pytest-asyncio like [this](https://github.com/pytest-dev/pytest-asyncio/issues/706), or something in autobahn needs changes.

**Comment by oberstet** [comment]
@yan12125 thanks a lot for tracking this down! I had a peek, and it might be spot on. the breaking change

https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.23.0

relates to **event_loop_policy**, which needs to be adjusted similar to

https://github.com/pytest-dev/pytest-asyncio/pull/662/files

**Comment by om26er** [comment]
@Mahad-10, can you look into the CI failures and create a PR for that?

**Comment by yan12125** [comment]
> @Mahad-10, can you look into the CI failures and create a PR for that?

FWIW, my WIP patches may be useful: https://github.com/crossbario/autobahn-python/compare/master...yan12125:autobahn-python:pytest-async-0.23

**Comment by oberstet** [comment]
I hate it. where did GH move the "rerun tests" button?

grafik

----

anyways. a merge commit of this PR should now actually run green. hope so.

**Pull request merged**
