### PR TITLE
 Allow tests to pass without XBR dependencies

### LINKED ISSUE #1579: Allow tests to pass without XBR dependencies
For version 22.5.1, tests fail if XBR dependencies are not installed:

<details>
<summary>
Test failures
</summary>

```
$ USE_TWISTED=1 PYTHONPATH=.:build/lib.linux-x86_64-3.10 trial autobahn
(...omitted...)
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/twisted/trial/runner.py", line 598, in loadPackage
    module = modinfo.load()
  File "/usr/lib/python3.10/site-packages/twisted/python/modules.py", line 390, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python3.10/site-packages/twisted/python/reflect.py", line 298, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python3.10/site-packages/twisted/python/reflect.py", line 245, in _importAndCheckStack
    raise excValue.with_traceback(excTraceback)
  File "/build/python-autobahn/src/autobahn-22.5.1/autobahn/xbr/test/test_xbr_frealm.py", line 13, in <module>
    from autobahn.xbr._secmod import SecurityModuleMemory, EthereumKey
  File "/build/python-autobahn/src/autobahn-22.5.1/autobahn/xbr/_secmod.py", line 35, in <module>
    from eth_account.account import Account
builtins.ModuleNotFoundError: No module named 'eth_account'

autobahn.xbr.test.test_xbr_frealm
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/twisted/trial/runner.py", line 598, in loadPackage
    module = modinfo.load()
  File "/usr/lib/python3.10/site-packages/twisted/python/modules.py", line 390, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python3.10/site-packages/twisted/python/reflect.py", line 298, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python3.10/site-packages/twisted/python/reflect.py", line 245, in _importAndCheckStack
    raise excValue.with_traceback(excTraceback)
  File "/build/python-autobahn/src/autobahn-22.5.1/autobahn/xbr/test/test_xbr_secmod.py", line 37, in <module>
    from py_eth_sig_utils.eip712 import encode_typed_data
builtins.ModuleNotFoundError: No module named 'py_eth_sig_utils'

autobahn.xbr.test.test_xbr_secmod
-------------------------------------------------------------------------------
```
</details>

Could you consider allowing tests to pass without XBR dependencies? For example, some other tests under autobahn/xbr first do `from autobahn.xbr import HAS_XBR`, and then import other XBR dependencies only when HAS_XBR is True. Relevant tests are also skipped if HAS_XBR is False.

I'm one of maintainers of official Arch Linux package [python-autobahn](https://archlinux.org/packages/community/x86_64/python-autobahn/). Maintaining XBR dependencies is a burden, so no related dependencies are picked into official repositories yet. I didn't use AUTOBAHN_STRIP_XBR introduced in #1371, so that users can still use autobahn.xbr if they installed necessary dependencies from unofficial packages.

### PR DESCRIPTION
**Pull request by yan12125**
Closes #1579

### CODE REVIEW

**Comment by oberstet** [comment]
great, thanks! only 2 minors comments / possible improvements you might try (pls see above) ..

**Comment by yan12125** [comment]
> only 2 minors comments / possible improvements

Hmm, I didn't see comments other than this one in this pull request. Did you leave them somewhere else?

**Comment by oberstet** [comment]
> Hmm, I didn't see comments other than this one in this pull request. Did you leave them somewhere else?

I did "start a review" and added comments to that - this is I can see my comments exactly above (not sure why you don't see it? who knows ..) let me Escher-Paste:

grafik

**Comment by yan12125** [comment]
> I did "start a review" and added comments to that - this is I can see my comments exactly above

Aha, you'll need to hit "Finish your review" to make those comments public :)

> `InvalidPayload` should not reside under the import guard

Thanks! I moved all such cases out.

> rgd `CryptosignKey`, this should reside under the `from autobahn.wamp.cryptosign import HAS_CRYPTOSIGN`

Yes, that makes sense! I changed to the approach used by current `autobahn/xbr/test/test_xbr_secmod.py` and put `HAS_XBR` and `HAS_CRYPTOSIGN` together. I noticed that `autobahn[xbr]` installs pynacl, so `HAS_CRYPTOSIGN` is always True when `HAS_XBR` is True. It may not be useful to have two separate checks.

**Review by oberstet — APPROVED** [review]

**Comment by yan12125** [comment]
Thanks for fast responses and constructive comments!

Now I can see review comments, by the way :)

**Comment by oberstet** [comment]
great, thanks for contributing! ah, and yes, I failed to hit "finish review", so that explains that;)

**Pull request merged**
