### PR TITLE
Ticket1075 revoke subscription force reregister

### PR DESCRIPTION
**Pull request by meejah**
Add the `force_reregister=` option to Registration, and the client-side behavior when getting a kicked registration message. Also an example of using the meta-API.

(Needs corresponding crossbar branch to actually-work)

### CODE REVIEW

**Comment by meejah** [comment]
Hmm, Twisted 12 and 13 have the "too old UnitTest" dependency (or something?) for `assertRaises` to work as a context-manager. Do we definitely care about those releases?

**Comment by oberstet** [comment]
@meejah awesome! comprehensive PR, nice work. I'll get to the corresponding CB PR.

**Comment by oberstet** [comment]
> Do we definitely care about those releases?

IMO, those Twisted versions are really old now, so +1 for moving our minimum version for Twisted in Autobahn (in Crossbar.io we are regularily pushing to the latest releases of all deps anyways).

Question is, what minimum version of Twisted should we support in AB?

**Comment by oberstet** [comment]
@meejah Twisted 15.4 or should we jump even further for minimum version?

**Comment by meejah** [comment]
Let's see, releases-wise Debian "stretch" just became stable so "jessie" is now old-stable so to make any packagers lives easiest, we'd support 16.6.x+ for "stretch" (latest stable). jessie/old-stable has 14.0.2 but there is jessie-backports that has 16.2.x

So I'd say anyone packaging for latest Debian should be satisfied with anything 16.x or higher. Ubuntu should be newer. So, 15.x should be fairly safe -- and we can always bump it up later if we run into problems? (That is, might as well keep 15 if it's straightforward...?)

**Comment by oberstet** [comment]
> So, 15.x should be fairly safe -- and we can always bump it up later if we run into problems

Yeah, sounds good! So we can kill 12.1 and 13.2 from Travis, which makes the CI run quicker - another nice side effect.

**Pull request merged**
