### PR TITLE
Ticket1392 internal attrs

### PR DESCRIPTION
**Pull request by meejah**
See #1392

### CODE REVIEW

**Comment by meejah** [comment]
(not sure what's up with the flake8 error; looks like an internal / tool error?)

**Comment by oberstet** [comment]
yeah, that looks like a tool bug. lemme try locally ..

**Comment by oberstet** [comment]
it does work for me locally - using the same flake8 that fails on CI, but using CPy 3.8 rather than CPy 3.5 (as CI runs):

```
flake8 installed: autobahn==20.6.1,flake8==3.8.3,flake8-polyfill==1.0.2,mccabe==0.6.1,pep8-naming==0.11.1,pycodestyle==2.6.0,pyflakes==2.2.0
flake8 run-test-pre: PYTHONHASHSEED='3547590259'
flake8 run-test: commands[0] | sh -c 'which python'
/home/oberstet/scm/crossbario/autobahn-python/.tox/flake8/bin/python
flake8 run-test: commands[1] | python -V
Python 3.8.2
flake8 run-test: commands[2] | flake8 --version
3.8.3 (mccabe: 0.6.1, naming: 0.11.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.2 on Linux
flake8 run-test: commands[3] | flake8 --ignore=E402,E501,E722,E741,N801,N802,N803,N805,N806,N815 --exclude 'autobahn/wamp/message_fbs.py,autobahn/wamp/gen/*' autobahn
______________________________________________________________ summary ______________________________________________________________
  flake8: commands succeeded
  congratulations :)
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ pip show flake8
Name: flake8
Version: 3.8.3
Summary: the modular source code checker: pep8 pyflakes and co
Home-page: https://gitlab.com/pycqa/flake8
Author: Tarek Ziade
Author-email: tarek@ziade.org
License: MIT
Location: /home/oberstet/cpy382_1/lib/python3.8/site-packages
Requires: pyflakes, mccabe, pycodestyle
Required-by: 
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ python -V
Python 3.8.2
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ 
```

**Comment by oberstet** [comment]
alright, that did the trick (use cpy3.8 rather than cpy 3.5) - whatever the real reason cpy3.5/flake8 .. it does work;)

https://travis-ci.com/github/crossbario/autobahn-python/builds/171797581

superseded by https://github.com/crossbario/autobahn-python/pull/1394

**Pull request closed without merging**
