### PR TITLE
Fix for #1327 - cancel Auto Ping Timeout 

### PR DESCRIPTION
**Pull request by DZabavchik**
and use inbound data frames in leu of PONG response

### CODE REVIEW

**Comment by oberstet** [comment]
so as discussed on https://github.com/crossbario/autobahn-python/issues/1327, this is a good approach we would like to have and merge

rgd the PR code

trivial issue is flake8 complaining https://travis-ci.org/crossbario/autobahn-python/jobs/655024730#L330

then, did you test this in real world? does it actually solve the issue (connection do indeed stay alive)?

my main worries beyond that: how does this change behave at scale? 

the reason is, that it that calls `self._cancelAutoPingTimeoutCall()` in the hot path of frame processing (on each received frame):

https://github.com/crossbario/autobahn-python/pull/1328/files#diff-83d22d16d23d299b646c94c41445c1aaR1676

also, Autobahn has sophisticated ping/pong handling ("batching") that originated from this discussion:

https://github.com/crossbario/autobahn-python/issues/642

we have to be sure this PR works with the batching ..

ideally we'd have mass-coms/scaling tests in our CI so we'd immediately know answers to above .. but we don't:(

**Comment by DZabavchik** [comment]
> then, did you test this in real world? does it actually solve the issue (connection do indeed stay alive)?
We had this fix in production since April 2017 (autobahn-python 16.1) .  I just noticed that PR was never filed for a well tested fix. https://github.com/NinjaRMM/autobahn-python/commit/6de1b43350bb4e6ce25c998076d2b2dfc38db472 

I participated in #642 also :)

There was no performance impact, as most of the time there is no pending PONG timeout.   We did see a huge improvement in reliability.

A slight improvement can be made by moving `if self.autoPingTimeoutCall:` outside of the function to save a call.

**Comment by DZabavchik** [comment]
Forgot to mention that because this is targeting large transfers and to minimize impact it is only done in `onFrameEnd`.   Updated PR with minor optimizations and fixes for travis-ci

**Comment by oberstet** [comment]
> We had this fix in production since April 2017 (autobahn-python 16.1)  ... We did see a huge improvement in reliability.

ah, perfect. thanks!

> I participated in #642 also :)

huh, right, sorry;)

thanks for the patch, and also your latest improvements to the PR!

gonna merge it now=)

**Pull request merged**
