### PR TITLE
wamp-scram

### PR DESCRIPTION
**Pull request by meejah**
Continuation of https://github.com/crossbario/autobahn-python/pull/956

This adds an onWelcome/on_welcome hook for authenticators to use and SCRAM uses it to check the server-signature as well as a few other fixups. Now matches the draft-spec (again).

### CODE REVIEW

**Comment by oberstet** [comment]
looks good! has the new onWelcome stuff.

rgd the fallout from that: maybe we could add a default (empty) implementation of onWelcome here https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L1129

**Comment by oberstet** [comment]
@meejah I would like to land the current state of WAMP-SCRAM in both AB and CB - do you think it is "ready"? There is some CI fallout that needs fixing, but then I would merge. Could you give me ping when to do a final review for merge? Or just assign me as reviewer when you feel ready ..

**Comment by meejah** [comment]
Okay I added the empty `onWelcome` and made a few fixups for the tests etc. Should be good to merge @oberstet

**Comment by oberstet** [comment]
perfect! great work. this is a very complete "prototype" I'd say;) now, cool, we have a WAMP-SCRAM spec and client/router prototype=)

**Comment by ecorm** [comment]
@meejah, @oberstet, except for channel binding, is WAMP-SCRAM now fully operational in Crossbar? Does it support dynamic authenticators?

**Comment by ecorm** [comment]
Oh, and thank you for implementing this! :heart:

**Comment by meejah** [comment]
It doesn't support dynamic authenticators (and no channel-binding, that's correct). Adding dynamic authenticators wouldn't be much more additional work but is not in master right now..

**Comment by ecorm** [comment]
@meejah For internal use, we can do ticket auth with client-side pre-hashing for now. We still have a lot of work to do for user management and permission control. We'd like to "drop in" WAMP-SCRAM later so that we gain the property of an eavesdropper not being able to impersonate a client.

**Pull request merged**
