### PR TITLE
prepare release

### PR DESCRIPTION
**Pull request by oberstet**

### CODE REVIEW

**Comment by oberstet** [comment]
so pypy fails on bitarray building https://github.com/crossbario/autobahn-python/actions/runs/4575675531/jobs/8078803377?pr=1617

**Comment by stumpylog** [comment]
In case you haven't already seen it: ilanschnell/bitarray/issues/188

**Comment by oberstet** [comment]
@stumpylog no, I haven't had seen that! yeah, it seems to be fixed on upstream master. let me give it a try ..

**Comment by oberstet** [comment]
@stumpylog unfort., still runs into issues: https://github.com/ilanschnell/bitarray/issues/188#issuecomment-1527746833

**Comment by logicsys** [comment]
https://github.com/ilanschnell/bitarray/issues/188#issuecomment-1569240742

**Comment by logicsys** [comment]
That PR has been merged into bitarray master now, if you want to try again on your side oberstet?

**Comment by oberstet** [comment]
@logicsys oh, ah, that sounds good! I will try again ..

**Comment by oberstet** [comment]
```
  Building wheel for bitarray (setup.py): started
  Building wheel for bitarray (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/__init__.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/util.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/test_util.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/bitarray.h -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/pythoncapi_compat.h -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/test_data.pickle -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/py.typed -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/util.pyi -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/__init__.pyi -> build/lib.linux-x86_64-3.9/bitarray
      running build_ext
      building 'bitarray._bitarray' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/bitarray
      gcc -pthread -DNDEBUG -O2 -fPIC -I/opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.9/bitarray/_bitarray.o
      In file included from /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/Python.h:123,
                       from bitarray/_bitarray.c:12:
      /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/pypy_decl.h:648:29: error: static declaration of ‘PyPyObject_CallNoArgs’ follows non-static declaration
        648 | #define PyObject_CallNoArgs PyPyObject_CallNoArgs
            |                             ^~~~~~~~~~~~~~~~~~~~~
      bitarray/pythoncapi_compat.h:395:1: note: in expansion of macro ‘PyObject_CallNoArgs’
        395 | PyObject_CallNoArgs(PyObject *func)
            | ^~~~~~~~~~~~~~~~~~~
      /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/pypy_decl.h:648:29: note: previous declaration of ‘PyPyObject_CallNoArgs’ with type ‘struct _object *(struct _object *)’
        648 | #define PyObject_CallNoArgs PyPyObject_CallNoArgs
            |                             ^~~~~~~~~~~~~~~~~~~~~
      /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/pypy_decl.h:649:30: note: in expansion of macro ‘PyObject_CallNoArgs’
        649 | PyAPI_FUNC(struct _object *) PyObject_CallNoArgs(struct _object *arg0);
            |                              ^~~~~~~~~~~~~~~~~~~
      /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/pypy_decl.h:652:29: error: static declaration of ‘PyPyObject_CallOneArg’ follows non-static declaration
        652 | #define PyObject_CallOneArg PyPyObject_CallOneArg
            |                             ^~~~~~~~~~~~~~~~~~~~~
      bitarray/pythoncapi_compat.h:406:1: note: in expansion of macro ‘PyObject_CallOneArg’
        406 | PyObject_CallOneArg(PyObject *func, PyObject *arg)
            | ^~~~~~~~~~~~~~~~~~~
      /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/pypy_decl.h:652:29: note: previous declaration of ‘PyPyObject_CallOneArg’ with type ‘struct _object *(struct _object *, struct _object *)’
        652 | #define PyObject_CallOneArg PyPyObject_CallOneArg
            |                             ^~~~~~~~~~~~~~~~~~~~~
      /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/pypy_decl.h:653:30: note: in expansion of macro ‘PyObject_CallOneArg’
        653 | PyAPI_FUNC(struct _object *) PyObject_CallOneArg(struct _object *arg0, struct _object *arg1);
            |                              ^~~~~~~~~~~~~~~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
  Running setup.py clean for bitarray
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bitarray
```

**Comment by logicsys** [comment]
strange, is that [oberstet:v23-3-1] still trying to pull the latest available bitarray from pypi? rather than direct from bitarrays github master?

if so we may just have to wait for bitarray to get a new release published to pypi

**Comment by oberstet** [comment]
> strange, is that [oberstet:v23-3-1] still trying to pull the latest available bitarray from pypi? rather than direct from bitarrays github master?

yes, it is, and there had been some new commits upstream ... and no bitarray 2.7.5 yet ... lets try trunk

**Comment by oberstet** [comment]
same issue https://github.com/crossbario/autobahn-python/actions/runs/5171042814/jobs/9314338930?pr=1617#step:8:150

**Comment by logicsys** [comment]
tox is still not using the bitarray github master, its still trying to use the latest available pypi package, perhaps add:

`    ; UNTIL bitarray is released on pypi with pypy fixes
    git+https://github.com/ilanschnell/bitarray.git`

to tox.ini under [testenv] ?

**Comment by oberstet** [comment]
> tox is still not using the bitarray github master,  ...

you are right. :(

it is ignoring https://github.com/crossbario/autobahn-python/pull/1617/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R122 likely because it first resolves to bitarray from another dependency before it gets to installing it directly

anyways: I've added it to tox directly as you suggested .. lets see. I really hope this solves it. I am kinda tired of all this dependency time wasting. there is nothing to be learned other than that python dep mgmt and packaging is broken. nothing new;)

**Comment by oberstet** [comment]
@logicsys https://pypi.org/project/autobahn/23.6.1/ =) thanks for helping!

**Comment by logicsys** [comment]
Yeah I hear you there for python deps, should be easier than this haha

Looks like bitarray has had a new release published to pypi, that includes the pypy fix:

2023-06-10   2.7.5:
-------------------
  * fix for pypy3.9-v7.3.11, #198 (fixes #188)
  * enable building wheels for PyPy

**Pull request merged**
