### PR TITLE
add docs for parameters to component.py

### PR DESCRIPTION
**Pull request by markope**
Add documentation for component transport configuration

### CODE REVIEW

**Comment by om26er** [comment]
At one stage we should make an effort to move towards the Type Hinting instead of docstrings, we may not be there till python2 support gets removed and we become python 3.5+ only.

**Comment by om26er** [comment]
There seems to be a flake8 error, you need to fix that for the CI.

**Comment by markope** [comment]
Some test fails now. I would say this has nothing to do with my changes
Travis Testoutput:
```
[FAIL]
Traceback (most recent call last):
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 605, in run
    testMethod()
  File "/home/travis/build/crossbario/autobahn-python/.tox/py35-tw189/lib/python3.5/site-packages/autobahn/test/test_rng.py", line 87, in test_non_depleting
    self.assertTrue(skeys[0] > 10)
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
builtins.AssertionError: False is not true
autobahn.test.test_rng.TestEntropy.test_non_depleting
```

**Comment by oberstet** [comment]
@markope looks good, thanks! (the remaining failed test: yep, not related)

**Comment by om26er** [comment]
I reported an issue for that test failure last night https://github.com/crossbario/autobahn-python/issues/1278

**Pull request merged**
