### PR TITLE
add python 3.8 compatibility

### PR DESCRIPTION
**Pull request by om26er**
Fixes https://github.com/crossbario/autobahn-python/issues/1193

### CODE REVIEW

**Comment by oberstet** [comment]
no, this is wrong: it exports new symbols (get_clock) which are then used on linux too - where is (if any) should use the existing rtime

**Comment by oberstet** [comment]
pls see my comment here https://github.com/crossbario/autobahn-python/issues/1193#issuecomment-543565756

**Comment by om26er** [comment]
@oberstet do we also want to deal with examples as well, because they use `time.clock()`, if not, then yes, the change can be as simple as that.

**Comment by oberstet** [comment]
ah, right. the examples should use `autobahn.util.rtime` ..

**Pull request closed without merging**
