### PR TITLE
Check first and then do increment

### PR DESCRIPTION
**Pull request by SunFulong**
Wrapping around at the boundary should do check first.

### CODE REVIEW

**Comment by oberstet** [comment]
This is wrong. It won't create an ID 9007199254740992. It is also unnecessary, the code as it stands is correct.

**Comment by SunFulong** [comment]
> It won't create an ID 9007199254740992.

Although it won't created, but it can be reached at previous round.

**Comment by oberstet** [comment]
> Although it won't created, but it can be reached at previous round.

yes, you are right actually, it would spit out 9007199254740992. however, I stand by my other comment: it is unnecessary (IOW: the PR code does not change the functional behavior in any way. and non-functional behavior .. performance .. I am not convinced it would be an improvement ... or even necessary anyways.

if you file a PR that changes the `0` to `1` to fix the bug I mentioned above, that would be highly welcome! I'd merged it right away ...

**Comment by SunFulong** [comment]
> if you file a PR that changes the 0 to 1 to fix the bug

See #1637

**Pull request closed without merging**
