### PR TITLE
Fix argument type check in sendMessage

### PR DESCRIPTION
**Pull request by 0xfadeef**

### CODE REVIEW

**Comment by 0xfadeef** [comment]
Are these type checks really necessary though?

**Comment by om26er** [comment]
I peaked inside the code and the change looks good to me :+1:

**Comment by meejah** [comment]
yeah, also `assert` goes away if you happen to use "optimized". And the checks should probably use `isinstance` not comparing to types ... but also they do provide some checks / sanity.

*Ideally*, we'd probably convert these all to mypy or similar these days (bear in mind Autobahn started in Python2 era).

**Comment by meejah** [comment]
thanks for the patch!

**Pull request merged**
