### PR TITLE
Remove meaningless assertions

### PR DESCRIPTION
**Pull request by sergio-bershadsky**

### CODE REVIEW

**Comment by oberstet** [comment]
what do you mean with "meaningless"?

**Comment by sergio-bershadsky** [comment]
There is no any case when `*args` or `**kwargs`  will be equal to None or it will no be type of tuple or dict.

**Comment by oberstet** [comment]
> There is no any case when *args or **kwargs will be equal to None or it will not be type of tuple or dict.

that is exactly what the assert test for

**Comment by oberstet** [comment]
aah, you mean

```
 def progress(*args, **kwargs):
```

in this specific function: true

for the others: not true

**Comment by sergio-bershadsky** [comment]
Please follow python manual. *[anything] are always tuple (empty to filled) so **[anything] are always dicts to need to check it

**Comment by sergio-bershadsky** [comment]
This "meaningless" touches all editing I sent

**Pull request closed without merging**
